# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Package

build:
  project: PlantUmlStudio.sln
  verbosity: minimal               # MSBuild verbosity level


# scripts to run before build
before_build:
  - git submodule update --init --recursive
  - nuget restore


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - Tests.Unit.dll


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: PlantUmlStudio.Setup\bin\$(CONFIGURATION)\PlantUmlStudio.msi