//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantUmlEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPath {
            get {
                return ((string)(this["LastPath"]));
            }
            set {
                this["LastPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GraphVizLocation {
            get {
                return ((string)(this["GraphVizLocation"]));
            }
            set {
                this["GraphVizLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://downloads.sourceforge.net/sourceforge/plantuml/plantuml.jar")]
        public global::System.Uri DownloadUrl {
            get {
                return ((global::System.Uri)(this["DownloadUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\PlantUML\\plantuml.jar")]
        public string PlantUmlLocation {
            get {
                return ((string)(this["PlantUmlLocation"]));
            }
            set {
                this["PlantUmlLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".puml")]
        public string PlantUmlFileExtension {
            get {
                return ((string)(this["PlantUmlFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://plantuml.sourceforge.net/plantumlVersionRss.xml")]
        public global::System.Uri PlantUmlVersionSource {
            get {
                return ((global::System.Uri)(this["PlantUmlVersionSource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".*version (?<version>\\d{4,5})[\\s]+.*")]
        public string PlantUmlRemoteVersionPattern {
            get {
                return ((string)(this["PlantUmlRemoteVersionPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\PlantUML.xshd")]
        public string PlantUmlHighlightingDefinition {
            get {
                return ((string)(this["PlantUmlHighlightingDefinition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".*version (?<version>\\d{4,5})[\\s].*")]
        public string PlantUmlLocalVersionPattern {
            get {
                return ((string)(this["PlantUmlLocalVersionPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".*version[\\s]+(?<version>.+)[\\s]+.*")]
        public string GraphVizLocalVersionPattern {
            get {
                return ((string)(this["GraphVizLocalVersionPattern"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RememberOpenFiles {
            get {
                return ((bool)(this["RememberOpenFiles"]));
            }
            set {
                this["RememberOpenFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OpenFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OpenFiles"]));
            }
            set {
                this["OpenFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveEnabled {
            get {
                return ((bool)(this["AutoSaveEnabled"]));
            }
            set {
                this["AutoSaveEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:30:00")]
        public global::System.TimeSpan AutoSaveInterval {
            get {
                return ((global::System.TimeSpan)(this["AutoSaveInterval"]));
            }
            set {
                this["AutoSaveInterval"] = value;
            }
        }
    }
}
