//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantUmlEditor.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlantUmlEditor.View.SettingsViewResources", typeof(SettingsViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow vertical scrolling beyond content.
        /// </summary>
        internal static string AllowScrollingBelowContentLabel {
            get {
                return ResourceManager.GetString("AllowScrollingBelowContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to allow vertical srolling past the end of a text editor&apos;s content..
        /// </summary>
        internal static string AllowScrollingBelowContentToolTip {
            get {
                return ResourceManager.GetString("AllowScrollingBelowContentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically save changes to open diagrams..
        /// </summary>
        internal static string AutoSaveCheckBoxToolTip {
            get {
                return ResourceManager.GetString("AutoSaveCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of time between automatic saves of a diagram, in seconds..
        /// </summary>
        internal static string AutoSaveIntervalValueToolTip {
            get {
                return ResourceManager.GetString("AutoSaveIntervalValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSave every.
        /// </summary>
        internal static string AutoSaveLabelPrefix {
            get {
                return ResourceManager.GetString("AutoSaveLabelPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string AutoSaveLabelSuffix {
            get {
                return ResourceManager.GetString("AutoSaveLabelSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Recent Files.
        /// </summary>
        internal static string ClearRecentFilesButton {
            get {
                return ResourceManager.GetString("ClearRecentFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string EditorTabTitle {
            get {
                return ResourceManager.GetString("EditorTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Cut or Copy to entire line if there is no selection.
        /// </summary>
        internal static string EmptySelectionCopiesEntireLineLabel {
            get {
                return ResourceManager.GetString("EmptySelectionCopiesEntireLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the current selection contains no text, a Cut or Copy operation affects the entire line the cursor resides on..
        /// </summary>
        internal static string EmptySelectionCopiesEntireLineToolTip {
            get {
                return ResourceManager.GetString("EmptySelectionCopiesEntireLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable virtual space.
        /// </summary>
        internal static string EnableVirtualSpaceLabel {
            get {
                return ResourceManager.GetString("EnableVirtualSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to use virtual space in the text editor..
        /// </summary>
        internal static string EnableVirtualSpaceToolTip {
            get {
                return ResourceManager.GetString("EnableVirtualSpaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable word wrap.
        /// </summary>
        internal static string EnableWordWrapLabel {
            get {
                return ResourceManager.GetString("EnableWordWrapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to wrap long lines..
        /// </summary>
        internal static string EnableWordWrapToolTip {
            get {
                return ResourceManager.GetString("EnableWordWrapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTabTitle {
            get {
                return ResourceManager.GetString("GeneralTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight current line.
        /// </summary>
        internal static string HighlightCurrentLineLabel {
            get {
                return ResourceManager.GetString("HighlightCurrentLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to highlight the line in which the cursor currently resides..
        /// </summary>
        internal static string HighlightCurrentLineToolTip {
            get {
                return ResourceManager.GetString("HighlightCurrentLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember up to .
        /// </summary>
        internal static string MaxRecentFilesLabelPrefix {
            get {
                return ResourceManager.GetString("MaxRecentFilesLabelPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most recent files.
        /// </summary>
        internal static string MaxRecentFilesLabelSuffix {
            get {
                return ResourceManager.GetString("MaxRecentFilesLabelSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of entries to keep in the recent files list..
        /// </summary>
        internal static string MaxRecentFilesToolTip {
            get {
                return ResourceManager.GetString("MaxRecentFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember open files.
        /// </summary>
        internal static string RememberOpenFilesLabel {
            get {
                return ResourceManager.GetString("RememberOpenFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen the diagram files that were open the last time the application closed at start-up..
        /// </summary>
        internal static string RememberOpenFilesToolTip {
            get {
                return ResourceManager.GetString("RememberOpenFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show line numbers.
        /// </summary>
        internal static string ShowLineNumbersLabel {
            get {
                return ResourceManager.GetString("ShowLineNumbersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to show line numbers in the text editor..
        /// </summary>
        internal static string ShowLineNumbersToolTip {
            get {
                return ResourceManager.GetString("ShowLineNumbersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
